### ISSUE TITLE
showVLAN showVRF and showSupernetOnly became int in phpIPAM version 1.6.0 

### ISSUE THREAD

**Issue by chavan-dinesh** [lord-kyron/terraform-provider-phpipam#93]
showVLAN showVRF and showSupernetOnly became int in phpIPAM version 1.6.0  causing provider to fail

```
│ Error: JSON parsing error: json: cannot unmarshal number into Go struct field Section.showVLAN of type string - Response data: [{"id":3,"name":"XXXX","description":"XXXX","masterSection":0,"permissions":"{\"2\":\"2\",\"3\":\"1\"}","strictMode":"1","subnetOrdering":"default","order":null,"editDate":"2024-06-10 18:52:52","showVLAN":1,"showVRF":1,"showSupernetOnly":1,"DNS":null,"showSubnet":1}]
```

Previous versions of phpIPAM were returning BoolIntString but latest version not doing so!

Same output from phpIPAM 1.4.5:

```
{"code":200,"success":true,"data":[{"id":"26","name":"XXXX","description":"XXXX","masterSection":"0","permissions":"[]","strictMode":"1","subnetOrdering":"default","order":null,"editDate":"2021-11-17 12:05:24","showVLAN":"1","showVRF":"1","showSupernetOnly":"1","DNS":null}],"time":0.004}

```

As you can see API call from 1.4.5 version returning showVLAN , showVRF and showSupernetOnly as BoolIntString.
Not sure who should fix it either you from provider side or phpIPAM from API side :)
But terraform provider is breaking due to this.

**Comment by d-costa** [comment]
I'm also having this issue.

```
Terraform v1.8.5
on linux_amd64
+ provider registry.terraform.io/lord-kyron/phpipam v1.6.2
```

Looks like we're waiting for a release to include this change https://github.com/phpipam/phpipam/issues/4043#issuecomment-2093611911 which should fix this issue @pavel-z1 ?

**Comment by CapMousse** [comment]
Same issue here

```
Terraform v1.5.7
on darwin_arm64
+ provider registry.terraform.io/lord-kyron/phpipam v1.6.2
```

**Comment by chavan-dinesh** [comment]
@d-costa Similar issue https://github.com/lord-kyron/terraform-provider-phpipam/issues/84 already closed with comments as new release will have backward compatibility!
Am using latest version of provider i.e. 1.6.2 (still facing issue) , Do we know what we should do for the backward compatibility  ?

**Comment by lucasdk3** [comment]
Have a solution for this problem?

**Comment by Marquis79** [comment]
I think the problem is not in the terraform provider but in the database phpipam conversion script when installing version 1.6.0. In tinyint type fields, instead of having the value 0, there is now the value \u0000 which causes a problem for the terraform requests. The solution is to delete the entry in phpipam and recreate the entry with terraform (terraform put the value 0 back into fields) or simply make a modification to the entry in phpipam to reset the value to 0 in the tinyint type fields.

**Comment by lord-kyron** [comment]
@pavel-z1 FYI

**Comment by yeswexav** [comment]
I reproduced this issue. It is not related specifically to 1.6.0, but rather to php8 support (that is included with 1.6.0).

If you run 1.6.0 with php7, there is no issue. With php8+, the ints in the json response of the API are encoded as json ints, instead of string before.
Here is an example of output for a `sections` resource
```shell
sdiff -s php8.json php7.json
"id": 3,						     |	     "id": "3",
      "masterSection": 0,				     |	     "masterSection": "0",
      "showSubnet": 1,					     |	     "showSubnet": "1",
      "showVLAN": 0,					     |	     "showVLAN": "0",
      "showVRF": 0,					     |	     "showVRF": "0",
      "showSupernetOnly": 0,				     |	     "showSupernetOnly": "0"
```      
I guess the provider is expecting ints encoded as string ("showVLAN": "0"), like before with php7, instead of int: ( "showVLAN": 0), that causes the unmarshal error :  Error: JSON parsing error: json: cannot unmarshal number into Go struct field Section.showVLAN of type string -

**Comment by pavel-z1** [comment]
Hi @chavan-dinesh @d-costa @CapMousse @lucasdk3 @Marquis79 

This issue was discussed previously here https://github.com/lord-kyron/terraform-provider-phpipam/issues/84
PHPIPAM changed API fields format due to migration to PHP 8 without back compatibility

Back compatibility was added:
- from PHPIPAM team side https://github.com/phpipam/phpipam/issues/4043 
- in this project https://github.com/lord-kyron/terraform-provider-phpipam/pull/90

Now, to make it all work, the PHPIPAM team needs to release a new version with this fix.

We have been expecting this action from the PHPIPAM team since May.
You can additionally create a request to the PHPIPAM project https://github.com/phpipam/phpipam/issues to release new minor version with fix https://github.com/phpipam/phpipam/commit/11a5ea0bbbe67b12f6db57b03e08560bfe1f7d65

Till the new release of PHPIPAM will be created you can use workaround for PHPIPAM 1.6.0 discribed here https://github.com/lord-kyron/terraform-provider-phpipam/issues/84#issuecomment-1959896507

**Comment by yeswexav** [comment]
works fine for we now with [phpipam release 1.7.3](https://github.com/phpipam/phpipam/releases/tag/v1.7.3) and php8

**Comment by lord-kyron** [comment]
Closing this as resolved — summarising for anyone who lands here later, since the answer ended up spread across the thread.

**Cause.** This was never really a provider bug. phpIPAM's move to PHP 8 (shipped with 1.6.0) changed the API to return integers as JSON numbers (`"showVLAN": 1`) instead of strings (`"showVLAN": "1"`). The provider's `BoolIntString` / `JSONIntString` types decode the string form, hence `cannot unmarshal number into Go struct field Section.showVLAN of type string`. Thanks @yeswexav for isolating it to PHP 8 rather than 1.6.0 itself.

**The fix took both sides:**

- Provider side — #90 (merged 2024-05-20, released in **v1.6.2**) sends the `api-stringify-results: 1` request header, asking the API for the legacy stringified format.
- phpIPAM side — https://github.com/phpipam/phpipam/issues/4043 made the server honour that header. This landed in the **1.7.x** series.

That's why people on provider v1.6.2 were still broken in mid-2024: they had the client half, but their server predated the server half. Confirmed working on phpIPAM 1.7.3 + PHP 8 (https://github.com/lord-kyron/terraform-provider-phpipam/issues/93#issuecomment-2618383760).

**If you still hit this:** upgrade phpIPAM to **1.7.0 or newer** and use provider **v1.6.2 or newer**. The provider relies on the server honouring `api-stringify-results`, so a phpIPAM in the 1.6.0–1.6.x range running PHP 8 will still fail regardless of provider version. The workaround for those stuck on 1.6.x is in https://github.com/lord-kyron/terraform-provider-phpipam/issues/84#issuecomment-1959896507.

Noting one known rough edge rather than leaving it undocumented: the provider currently depends entirely on that header, because the SDK's `BoolIntString`/`JSONIntString` decoders reject bare JSON numbers outright. Making them accept both forms would remove the phpIPAM version coupling, but it belongs upstream in [pavel-z1/phpipam-sdk-go](https://github.com/pavel-z1/phpipam-sdk-go) rather than here. Worth a separate issue if anyone is still stuck on 1.6.x — please reopen or file a new one if so.
